name: Test Action for {{NAME}}
on:
  push:
    paths:
      - "{{NAME}}/**"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Run test for ${{NAME}}"
      - run: echo "ğŸ This job's status is ${{ job.status }}."