name: Test Action for Service B
on:
  push:
    paths:
      - "service-b/**"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Run test for Service B"
      - run: echo "ğŸ This job's status is ${{ job.status }}."